ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS membership_purchased BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS membership_plan TEXT,
  ADD COLUMN IF NOT EXISTS membership_cost NUMERIC NOT NULL DEFAULT 0;
